### ISSUE TITLE
4.1.18 Impove ui display

### ISSUE THREAD

**Issue by saluttolove** [sopra-fs24-group-18/sopra-fs24-group-18-client#92]

**Comment by binxxxxx** [comment]
b504649c2651ce99d2900ecefa621593b4e0429d

**Comment by binxxxxx** [comment]
2cde50358c2e59dc0b9c7a40209914062d0603c2

**Comment by binxxxxx** [comment]
281360d0270fe46f01c7459829e3e74378c57420

**Comment by binxxxxx** [comment]
ad324a1a236db593edbd62da91fd47948894f573

**Comment by binxxxxx** [comment]
ba422c627ac25cfb0a3177439d2a2558809b896f

**Comment by binxxxxx** [comment]
c7bb08f808deaa89d0ef6e1f586b0b833c57b594
a2dda584c79a789158bbccf90512cbba6c19b745
