### ISSUE TITLE
4.1.23 Update Client-side readMe

### ISSUE THREAD

**Issue by saluttolove** [sopra-fs24-group-18/sopra-fs24-group-18-client#97]

**Comment by binxxxxx** [comment]
ab6c83894e9b0430672025814b6aa60510ae5f26
73393e5c58f5967b454ddc3ea773b20e83ac55cb
66f8d235fec6e2588719186c6bc4db404bc4742f
3bc634353c8dfb2eafa7ea16a4b63b06cb6005aa
8f946989fcf824d19047a03ecc6c0411f8dc02cc

**Comment by binxxxxx** [comment]
ab6c83894e9b0430672025814b6aa60510ae5f26
73393e5c58f5967b454ddc3ea773b20e83ac55cb
66f8d235fec6e2588719186c6bc4db404bc4742f
3bc634353c8dfb2eafa7ea16a4b63b06cb6005aa
8f946989fcf824d19047a03ecc6c0411f8dc02cc

**Comment by saluttolove** [comment]
bc69d88
45599a7
51d824e
df4960c

**Comment by saluttolove** [comment]
815c9b8

**Comment by saluttolove** [comment]
df4960c3
